		<div id="policy" class="politica-con">
				<div class="title-heading-con">
					<h1 data-lang="Политика конфиденциальности" data-lang_en="Privacy policy" class="anim-left title-heading">Политика конфиденциальности</h1>
					<a href="/assets/img/privacy-policy.pdf" target="_blank"><button data-lang="Политика конфиденциальности" data-lang_en="Privacy policy" class="btn btn-download">Политика конфиденциальности</button></a>
				</div>
				<h2  id="description" data-lang="Настоящим, в соответствии с Федеральным законом № 152-ФЗ «О персональных данных» от 27.07.2006 года, Вы подтверждаете свое согласие на обработку компанией Обществом с ограниченной ответственностью «МЕКАГРО ГРУП» (далее по тексту — ООО «МЕКАГРО ГРУП») персональных данных: сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, передачу исключительно в целях информирования Вас об услугах  ООО «МЕКАГРО ГРУП», как это описано ниже, блокирование, обезличивание, уничтожение. <br><br>
				Настоящим при размещении (вводе) своих персональных данных на Интернет-сайте ООО «МЕКАГРО ГРУП» даю свое согласие Обществу с ограниченной ответственностью ООО «МЕКАГРО ГРУП» (Россия,  г. Краснодар, посёлок Белозёрный, Елизаветинское шоссе, ул. Полевая ) согласие на обработку своих персональных данных, указанных при регистрации, и подтверждаю, что даю такое согласие, действуя в своей воле и в своем интересе.<br>
				Настоящим подтверждаю, что данное согласие на обработку персональных данных дается мною в целях получения услуг, оказываемых Компанией. Под персональными данными понимается информация, указываемая при регистрации на интернет-сайте  <a href='https://mecagrogrup.ru/'>https://mecagrogrup.ru/</a> Настоящее согласие предоставляется на осуществление любых действий в отношении персональных данных, которые необходимы и желаемы для достижения вышеуказанной цели, включая, без ограничения, сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, распространение (в том числе передача), обезличивание, блокирование, уничтожение, трансграничную передачу персональных данных, а также осуществление любых иных действий с персональными данными с учетом действующего законодательства Российской Федерации об обеспечении конфиденциальности персональных данных и безопасности персональных данных при их обработке. Обработка персональных данных осуществляется  ООО «МЕКАГРО ГРУП» с использованием средств автоматизации, в том числе с использованием информационных технологий и технических средств, включая средства вычислительной техники, информационно-вычислительные комплексы и сети, средства и системы передачи, приема и обработки персональных данных (средства и системы звукозаписи, звукоусиления, звуковоспроизведения, переговорные и телевизионные устройства, средства изготовления, тиражирования документов и другие технические средства обработки речевой, графической, видео- и буквенно-цифровой информации), программные средства (операционные системы, системы управления базами данных и т. п.), средства защиты информации, применяемые в информационных системах, а также без использования средств автоматизации.<br><br>
				Настоящее согласие на обработку персональных данных дается бессрочно и может быть отозвано посредством направления письменного заявления в адрес  ООО «МЕКАГРО ГРУП» по адресу, указанным выше. Настоящим признаю и подтверждаю, что с правами и обязанностями в соответствии с Федеральным законом «О персональных данных», в т. ч. порядком отзыва согласия на обработку персональных данных ознакомлен.  Настоящее согласие действует в течение всего периода хранения персональных данных, если иное не предусмотрено законодательством Российской Федерации." 
				data-lang_en="Hereby, in accordance with Federal Law No. 152-FZ 'On Personal Data' dated 27.07.2006, you confirm your consent to the processing of personal data by the Limited Liability Company MEKAGRO GROUP (hereinafter referred to as LLC MEKAGRO GROUP): collection, systematization, accumulation, storage, clarification (updating, modification), use, transfer solely for the purpose of informing you about the services of MEKAGRO GROUP LLC, as described below, blocking, depersonalization, destruction. <br><br>
				Hereby, when posting (entering) my personal data on the MEKAGRO GROUP LLC website, I give my consent to the Limited Liability Company MEKAGRO GROUP LLC (Russia, Krasnodar, Belozerny settlement, Elizavetinskoe Highway, Polevaya Street) consent to the processing of my personal data specified during registration, and confirm that I give such consent, acting in my own will and in my own interest.<br>
				I hereby confirm that this consent to the processing of personal data is given by me in order to receive the services provided by the Company. Personal data refers to information provided during registration on the website <a href='https://mecagrogrup.ru /'>https://mecagrogrup.ru /</a> This consent is granted to perform any actions with respect to personal data that are necessary and desirable to achieve the above purpose, including, without limitation, collection, systematization, accumulation, storage, clarification (updating, modification), use, dissemination (including transfer), depersonalization, blocking, destruction, cross-border transfer of personal data. data, as well as the implementation of any other actions with personal data, taking into account the current legislation of the Russian Federation on ensuring the confidentiality of personal data and the security of personal data during their processing. The processing of personal data is carried out by MEKAGRO GROUP LLC using automation tools, including the use of information technologies and technical means, including computing equipment, information and computing complexes and networks, means and systems for transmitting, receiving and processing personal data (sound recording, sound reinforcement, sound reproduction, negotiation and television devices, means of production, replication of documents and other technical means of processing speech, graphic, video- and alphanumeric information), software tools (operating systems, database management systems, etc.), information security tools used in information systems, as well as without the use of automation tools.<br><br>
				This consent to the processing of personal data is given indefinitely and can be revoked by sending a written application to LLC 'MEKAGRO GROUP' at the address indicated above. I hereby acknowledge and confirm that I am familiar with the rights and obligations under the Federal Law 'On Personal Data', including the procedure for revoking consent to the processing of personal data.This consent is valid for the entire period of personal data storage, unless otherwise provided by the legislation of the Russian Federation.">

				Настоящим, в соответствии с Федеральным законом № 152-ФЗ «О персональных данных» от 27.07.2006 года, Вы подтверждаете свое согласие на обработку компанией Обществом с ограниченной ответственностью «МЕКАГРО ГРУП» (далее по тексту — ООО «МЕКАГРО ГРУП») персональных данных: сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, передачу исключительно в целях информирования Вас об услугах  ООО «МЕКАГРО ГРУП», как это описано ниже, блокирование, обезличивание, уничтожение. <br><br>
				Настоящим при размещении (вводе) своих персональных данных на Интернет-сайте ООО «МЕКАГРО ГРУП» даю свое согласие Обществу с ограниченной ответственностью ООО «МЕКАГРО ГРУП» (Россия,  г. Краснодар, посёлок Белозёрный, Елизаветинское шоссе, ул. Полевая ) согласие на обработку своих персональных данных, указанных при регистрации, и подтверждаю, что даю такое согласие, действуя в своей воле и в своем интересе.<br>
				Настоящим подтверждаю, что данное согласие на обработку персональных данных дается мною в целях получения услуг, оказываемых Компанией. Под персональными данными понимается информация, указываемая при регистрации на интернет-сайте  <a href="https://mecagrogrup.ru/">https://mecagrogrup.ru/</a> Настоящее согласие предоставляется на осуществление любых действий в отношении персональных данных, которые необходимы и желаемы для достижения вышеуказанной цели, включая, без ограничения, сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, распространение (в том числе передача), обезличивание, блокирование, уничтожение, трансграничную передачу персональных данных, а также осуществление любых иных действий с персональными данными с учетом действующего законодательства Российской Федерации об обеспечении конфиденциальности персональных данных и безопасности персональных данных при их обработке. Обработка персональных данных осуществляется  ООО «МЕКАГРО ГРУП» с использованием средств автоматизации, в том числе с использованием информационных технологий и технических средств, включая средства вычислительной техники, информационно-вычислительные комплексы и сети, средства и системы передачи, приема и обработки персональных данных (средства и системы звукозаписи, звукоусиления, звуковоспроизведения, переговорные и телевизионные устройства, средства изготовления, тиражирования документов и другие технические средства обработки речевой, графической, видео- и буквенно-цифровой информации), программные средства (операционные системы, системы управления базами данных и т. п.), средства защиты информации, применяемые в информационных системах, а также без использования средств автоматизации.<br><br>
				Настоящее согласие на обработку персональных данных дается бессрочно и может быть отозвано посредством направления письменного заявления в адрес  ООО «МЕКАГРО ГРУП» по адресу, указанным выше. Настоящим признаю и подтверждаю, что с правами и обязанностями в соответствии с Федеральным законом «О персональных данных», в т. ч. порядком отзыва согласия на обработку персональных данных ознакомлен.  Настоящее согласие действует в течение всего периода хранения персональных данных, если иное не предусмотрено законодательством Российской Федерации.
				</h2>
				<button   data-lang="далее" data-lang_en="read more" id="readMoreBtn">далее</button>
		</div>